# Form implementation generated from reading ui file 'C:\Users\Lenovo\PycharmProjects\K24406H\DoAnCuoiKy\ui\DailySummary.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Daily_Summary(object):
    def setupUi(self, Daily_Summary):
        Daily_Summary.setObjectName("Daily_Summary")
        Daily_Summary.resize(414, 236)
        self.centralwidget = QtWidgets.QWidget(parent=Daily_Summary)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(250, 225, 220);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_MaterialCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_MaterialCost.setGeometry(QtCore.QRect(210, 60, 191, 31))
        self.lineEdit_MaterialCost.setStyleSheet("background-color: rgb(255, 177, 161);")
        self.lineEdit_MaterialCost.setObjectName("lineEdit_MaterialCost")
        self.lineEdit_Revenue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Revenue.setGeometry(QtCore.QRect(210, 100, 191, 31))
        self.lineEdit_Revenue.setStyleSheet("background-color: rgb(255, 177, 161);")
        self.lineEdit_Revenue.setObjectName("lineEdit_Revenue")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_Profit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Profit.setGeometry(QtCore.QRect(210, 140, 191, 31))
        self.lineEdit_Profit.setStyleSheet("background-color: rgb(255, 177, 161);")
        self.lineEdit_Profit.setObjectName("lineEdit_Profit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        Daily_Summary.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Daily_Summary)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 26))
        self.menubar.setObjectName("menubar")
        Daily_Summary.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Daily_Summary)
        self.statusbar.setObjectName("statusbar")
        Daily_Summary.setStatusBar(self.statusbar)

        self.retranslateUi(Daily_Summary)
        QtCore.QMetaObject.connectSlotsByName(Daily_Summary)

    def retranslateUi(self, Daily_Summary):
        _translate = QtCore.QCoreApplication.translate
        Daily_Summary.setWindowTitle(_translate("Daily_Summary", "Daily Summary"))
        self.label.setText(_translate("Daily_Summary", "<html><head/><body><p align=\"center\">Daily Summary</p></body></html>"))
        self.label_2.setText(_translate("Daily_Summary", "<html><head/><body><p><span style=\" font-size:12pt;\">Total Material Cost:</span></p></body></html>"))
        self.label_3.setText(_translate("Daily_Summary", "<html><head/><body><p>Total Revenue:</p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("Daily_Summary", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Profit:</span></p></body></html>"))
