# Form implementation generated from reading ui file 'C:\Users\Lenovo\PycharmProjects\K24406H\DoAnCuoiKy\ui\ImportExport.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(540, 215)
        mainWindow.setStyleSheet("background-color: rgb(254, 255, 222);")
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(201, 255, 201);")
        self.label.setObjectName("label")
        self.lineEdit_Filename = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Filename.setGeometry(QtCore.QRect(30, 60, 481, 41))
        self.lineEdit_Filename.setStyleSheet("background-color: rgb(255, 219, 255);")
        self.lineEdit_Filename.setObjectName("lineEdit_Filename")
        self.pushButtoExport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtoExport.setGeometry(QtCore.QRect(220, 120, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtoExport.setFont(font)
        self.pushButtoExport.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButtoExport.setIconSize(QtCore.QSize(32, 20))
        self.pushButtoExport.setObjectName("pushButtoExport")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Import / Export"))
        self.label.setText(_translate("mainWindow", "Nhập tên file:"))
        self.pushButtoExport.setText(_translate("mainWindow", "Export"))
